services:
  # --- Symfony Services ---
  php_symfony:
    build:
      context: ./docker/php
    volumes:
      - ./symfony:/var/www/html
    depends_on:
      - database
    networks:
      - symfony_network

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data_symfony:/var/lib/postgresql/data
    networks:
      - symfony_network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    networks:
      - symfony_network

  nginx_symfony:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_symfony
    networks:
      - symfony_network

  # --- WordPress Services ---
  php_wordpress:
    image: wordpress:fpm
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
    networks:
      - wordpress_network

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data_wordpress:/var/lib/mysql
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - wordpress_network

  nginx_wordpress:
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/nginx/wordpress.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_wordpress
    networks:
      - wordpress_network

networks:
  symfony_network:
  wordpress_network:

volumes:
  db_data_symfony:
  db_data_wordpress:
